[package]
name = "database-enforcer"
author = "Eva Harris <mail@gastrodon.io>"
version = "0.1.0"
edition = "2018"

[dependencies.futures]
version = "~0.3"

[dependencies.mysql]
version = "~21.0"

[dependencies.tokio]
version = "~1.9"
features = ["full"]

[dependencies.walkdir]
version = "~2.3"
