name: Test

on:
  - push
  - pull_request
  - repository_dispatch

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Ref
        run: echo ${{ github.ref }}
      - name: Head ref
        run: echo ${{ github.head_ref }}
      - name: Cargo version
        run: cargo version

  awscli:
    runs-on: ubuntu-latest
    steps:
      - name: Get dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install curl unzip
      - name: Get zip
        run: curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /tmp/awscliv2.zip
      - name: Unzip
        run: unzip -d /tmp/awscli /tmp/awscliv2.zip
      - name: Install
        run: sudo /tmp/awscli/aws/install --update

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get dependencies
        run: cargo update
      - name: Build package
        run: cargo build --release

  clippy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Clippy
        run: cargo clippy

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Set up testing database
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: brane
          mysql root password: foobar2000
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        env:
          DATABASE_CONNECTION: "mysql://root:foobar2000@localhost/brane"
        run: cargo test

  docker-dockerhub:
    if: github.ref == 'refs/heads/master' && github.head_ref == ''
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    strategy:
      matrix:
        repo:
          - "${{ secrets.DOCKERHUB_USERNAME }}/brane-${{ github.event.repository.name }}"
        tag:
          - latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
      - name: Dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ matrix.repo }}:${{ matrix.tag }}

  docker-ecr:
    if: github.ref == 'refs/heads/master' && github.head_ref == ''
    runs-on: ubuntu-latest
    needs:
      - awscli
      - build
      - test
    strategy:
      matrix:
        repo:
          - public.ecr.aws/${{ secrets.ECR_NAMESPACE }}/brane-${{ github.event.repository.name }}-service
        tag:
          - latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
      - name: AWS config
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: ECR-public login
        run: >-
          aws ecr-public get-login-password --region us-east-1 |
          docker login --username AWS --password-stdin public.ecr.aws/${{ secrets.ECR_NAMESPACE }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ matrix.repo }}:${{ matrix.tag }}
